language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -r dev_requirements.txt
    - pip install coveralls
script:
    py.test --cov-report term-missing --cov=tolk -v tests/
after_success:
    coveralls
