tests:
    build: .
    volumes:
        - ./:/src
    working_dir: /src
    command:
        py.test tests/

docs:
    build: .
    volumes:
        - ./:/src
    command:
        sphinx-build -b html /src/docs/source /src/docs/build
